### ISSUE TITLE
zlib-sync install: ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by Shivam0887** [abalabahaha/zlib-sync#13]
I was trying to deploy my Next.js 14 project on Vercel. However, I got this error "zlib-sync install: ModuleNotFoundError: No module named 'distutils'". 
Official Python Docs states that: distutils is deprecated with removal planned for Python 3.12. In particular, setuptools is an enhanced alternative to distutils.
https://docs.python.org/3.10/library/distutils.html

![image](https://github.com/abalabahaha/zlib-sync/assets/83500384/3362d307-3e1a-48ca-9366-cd03697b4d6e)

Please resolve the issue as soon as possible.

**Comment by SuperchupuDev** [comment]
had this issue too, it's because the node-gyp version used is the one that comes with pnpm. updating to pnpm v9 solved it for me

**Comment by 3megabytesofhotram** [comment]
Updating pnpm to 9 also fixed it for me
